spring.application.name=account-service
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=SYSTEM
spring.datasource.password=Ritwik123

# ===============================
# === JPA Provider Settings =====
# ===============================
spring.jpa.properties.jpa.provider=org.eclipse.persistence.jpa.PersistenceProvider
spring.jpa.properties.eclipselink.logging.level=FINE
spring.jpa.properties.eclipselink.ddl-generation=create-or-extend-tables
spring.jpa.properties.eclipselink.target-database=Oracle
spring.jpa.show-sql=true
